"""
Central configuration file for the Godamwale AI Content Agent.
All adjustable values should be defined here.
"""

# ============================================================
# AI CONFIGURATION
# ============================================================

MODEL_NAME = "openai/gpt-4o"

# Maximum tokens generated by the AI
MAX_TOKENS = 2000


# ============================================================
# RAG CONFIGURATION
# ============================================================

# Approximate size of each retrieved text chunk
CHUNK_SIZE = 500

# Number of relevant chunks retrieved for a request
TOP_K_RESULTS = 3


# ============================================================
# WEBSITE READER
# ============================================================

# Maximum number of pages read from one website
MAX_WEBSITE_PAGES = 5

# Maximum number of websites allowed in the UI
MAX_WEBSITES = 10


# ============================================================
# CONTENT LIMITS
# ============================================================

# Maximum website content passed into AI processing
WEBSITE_CONTENT_LIMIT = 12000

# Maximum content used for SEO analysis
SEO_CONTENT_LIMIT = 8000

# Maximum approved company information used by modules
COMPANY_INFORMATION_LIMIT = 6000

# Maximum context supplied to individual AI modules
MODULE_CONTEXT_LIMIT = 6000

